import { ChartCart } from "components/ChartCard";
import { FormModal } from "components/FormModal";
import { MainLayout } from "components/MainLayout";
import { PerformanceCard } from "components/PerformanceCard";
import Head from "next/head";
import { useState } from "react";

export default function Dashboard() {
  const [showDialog, setShowDialog] = useState(false);

  const handleClick = () => setShowDialog(true);

  return (
    <div>
      <Head>
        <title>Kpi Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainLayout>
        <button onClick={handleClick}>On Click</button>
        <div className="grid grid-cols-3 gap-4">
          <div>
            <PerformanceCard />
          </div>
          <div className="col-span-2">
            <ChartCart />
          </div>
          <div className="w-full col-span-3 h-36 p-8 rounded-2xl bg-copper opacity-70"></div>
        </div>
      </MainLayout>
      <FormModal isOpen={showDialog} closeModal={() => setShowDialog(false)} />
    </div>
  );
}
