import { ChartWidget } from "components/organisms/ChartWidget";
import { PerformanceWidget } from "components/organisms/PerformanceWidget";
import { FormModal } from "components/organisms/FormModal";
import { KpiWidget } from "components/organisms/KpiWidget";
import { MainLayout } from "components/organisms/MainLayout";
import Head from "next/head";
import { useState } from "react";

export default function Dashboard() {
  const [showDialog, setShowDialog] = useState(false);

  const handleClick = () => setShowDialog(true);

  return (
    <>
      <Head>
        <title>Kpi Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <MainLayout>
        <button onClick={handleClick}>On Click</button>
        <div className="grid grid-cols-3 gap-4">
          <div className="col-span-1">
            <PerformanceWidget />
          </div>
          <div className="col-span-2">
            <ChartWidget />
          </div>
          <div className="col-span-3">
            <KpiWidget />
          </div>
        </div>
      </MainLayout>

      <FormModal isOpen={showDialog} closeModal={() => setShowDialog(false)} />
    </>
  );
}
